name: Linux

on:

  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'demo/**'
      - '.github/workflows/linux.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**'
      - 'demo/**'
      - '.github/workflows/linux.yml'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for actions/upload-release-asset to upload release asset
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        bits: [64]
        include:
        - bits: 64
          ARCH: "x86_64"
          ARCH_NAME: "amd64"
          COMPILER_PATH: "/user/bin"

    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - uses: mlugg/setup-zig@v2

    - name: Setup Environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install gcc-multilib
        sudo apt-get install -y --no-install-recommends libx11-dev mesa-common-dev libglx-dev libxcursor-dev mesa-vulkan-drivers libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev libgles2-mesa-dev libosmesa6-dev glslang-tools libvulkan-dev  xvfb

    - name: test C++
      run: |
        cd demo
        make
        make clean
        make CC=g++
      if: matrix.bits == 64

    - name: test Zig
      run: |
        cd demo && make CC="zig cc" NO_VULKAN=1
      if: matrix.bits == 64
